INSERT INTO rol (nombre) VALUES ('ADMIN');
INSERT INTO rol (nombre) VALUES ('GERENTE_SUCURSAL');
INSERT INTO rol (nombre) VALUES ('JEFE_TURNO');
INSERT INTO rol (nombre) VALUES ('REPONEDOR');
INSERT INTO rol (nombre) VALUES ('CAJERO');
INSERT INTO rol (nombre) VALUES ('ASISTENTE_SERVICIO');
INSERT INTO rol (nombre) VALUES ('CLIENTE');
